# Generated by Django 3.0 on 2021-11-29 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relations', '0002_auto_20211129_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='follower',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
