# Generated by Django 3.0 on 2021-11-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0003_relation_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='follower',
        ),
    ]
