# Generated by Django 3.0 on 2021-12-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20211128_1412'),
        ('relations', '0004_remove_relation_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='my_game_list',
            field=models.ManyToManyField(blank=True, to='games.Game'),
        ),
    ]
