# Generated by Django 3.0 on 2021-11-27 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='posts')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_games', to='games.Game')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
