# Generated by Django 3.0 on 2021-11-28 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20211128_1412'),
        ('posts', '0003_auto_20211128_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='games.Game'),
        ),
    ]
