# Generated by Django 3.0 on 2021-11-29 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_userfollowing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-pk']},
        ),
    ]
