# Generated by Django 3.0 on 2022-01-04 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamescores', '0002_gamescore_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamescore',
            name='attitude',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='humor',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='manner',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='physical',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='sense',
        ),
    ]
