# Generated by Django 3.0 on 2022-01-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('legue of legent', 'League Of Legend'), ('battleground', 'BattleGround'), ('diablo2', 'Diablo2')], max_length=140)),
                ('kind', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
