# Generated by Django 3.0 on 2021-11-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='kind',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(choices=[('legue of legent', 'League Of Legend'), ('battleground', 'BattleGround'), ('diablo2', 'Diablo2')], max_length=140),
        ),
    ]
